CREATE MEMORY TABLE PUBLIC.user(
id INTEGER IDENTITY NOT NULL PRIMARY KEY,
account VARCHAR(16),
password VARCHAR(64), 
gmt_created TIMESTAMP,
gmt_modified TIMESTAMP
);

SET DATABASE REFERENTIAL INTEGRITY FALSE;